<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migration\**" />
    <Compile Remove="wwwroot\meine-website\**" />
    <Compile Remove="wwwroot\NewFolder\**" />
    <Content Remove="Migration\**" />
    <Content Remove="wwwroot\meine-website\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="Migration\**" />
    <EmbeddedResource Remove="wwwroot\meine-website\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <None Remove="Migration\**" />
    <None Remove="wwwroot\meine-website\**" />
    <None Remove="wwwroot\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Pages\Error.cshtml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="fragen.json" />
    <Content Remove="Pages\Error.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
