// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchulungKK.Data;

#nullable disable

namespace SchulungKK.Migrations
{
    [DbContext(typeof(SchulungenDbContext))]
    [Migration("20260729073151_GruppenUndVideoverwaltung")]
    partial class GruppenUndVideoverwaltung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchulungKK.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IstAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LetzterLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RegistriertAm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername")
                        .IsUnique();

                    b.ToTable("Benutzer", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.BenutzerGruppe", b =>
                {
                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("GruppeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZugeordnetAm")
                        .HasColumnType("datetime2");

                    b.HasKey("BenutzerId", "GruppeId");

                    b.HasIndex("GruppeId");

                    b.ToTable("BenutzerGruppen", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.Gruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Gruppen", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.GruppeVideo", b =>
                {
                    b.Property<int>("GruppeId")
                        .HasColumnType("int");

                    b.Property<int>("SchulungsvideoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZugeordnetAm")
                        .HasColumnType("datetime2");

                    b.HasKey("GruppeId", "SchulungsvideoId");

                    b.HasIndex("SchulungsvideoId");

                    b.ToTable("GruppeVideos", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.QuizErgebnis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbgeschlossenAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Bestanden")
                        .HasColumnType("bit");

                    b.Property<int>("Gesamt")
                        .HasColumnType("int");

                    b.Property<decimal>("Prozent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Richtig")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("QuizErgebnisse", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.Schulungsvideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Dateiname")
                        .IsUnique();

                    b.ToTable("Schulungsvideos", (string)null);
                });

            modelBuilder.Entity("SchulungKK.Models.BenutzerGruppe", b =>
                {
                    b.HasOne("SchulungKK.Models.Benutzer", "Benutzer")
                        .WithMany("BenutzerGruppen")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchulungKK.Models.Gruppe", "Gruppe")
                        .WithMany("BenutzerGruppen")
                        .HasForeignKey("GruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Gruppe");
                });

            modelBuilder.Entity("SchulungKK.Models.GruppeVideo", b =>
                {
                    b.HasOne("SchulungKK.Models.Gruppe", "Gruppe")
                        .WithMany("GruppeVideos")
                        .HasForeignKey("GruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchulungKK.Models.Schulungsvideo", "Schulungsvideo")
                        .WithMany("GruppeVideos")
                        .HasForeignKey("SchulungsvideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gruppe");

                    b.Navigation("Schulungsvideo");
                });

            modelBuilder.Entity("SchulungKK.Models.QuizErgebnis", b =>
                {
                    b.HasOne("SchulungKK.Models.Benutzer", "Benutzer")
                        .WithMany("QuizErgebnisse")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("SchulungKK.Models.Benutzer", b =>
                {
                    b.Navigation("BenutzerGruppen");

                    b.Navigation("QuizErgebnisse");
                });

            modelBuilder.Entity("SchulungKK.Models.Gruppe", b =>
                {
                    b.Navigation("BenutzerGruppen");

                    b.Navigation("GruppeVideos");
                });

            modelBuilder.Entity("SchulungKK.Models.Schulungsvideo", b =>
                {
                    b.Navigation("GruppeVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
