// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchulungKK.Data;

#nullable disable

namespace SchulungKK.Migrations
{
    [DbContext(typeof(SchulungenDbContext))]
    partial class SchulungenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchulungKK.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LetzterLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Passwort")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RegistriertAm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername")
                        .IsUnique();

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("SchulungKK.Models.QuizErgebnis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbgeschlossenAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<bool>("Bestanden")
                        .HasColumnType("bit");

                    b.Property<int>("Gesamt")
                        .HasColumnType("int");

                    b.Property<decimal>("Prozent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Richtig")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.ToTable("QuizErgebnisse");
                });

            modelBuilder.Entity("SchulungKK.Models.QuizErgebnis", b =>
                {
                    b.HasOne("SchulungKK.Models.Benutzer", "Benutzer")
                        .WithMany("QuizErgebnisse")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");
                });

            modelBuilder.Entity("SchulungKK.Models.Benutzer", b =>
                {
                    b.Navigation("QuizErgebnisse");
                });
#pragma warning restore 612, 618
        }
    }
}
